---
- name: install required packages
  yum:
    name: "{{ pxe_pkgs }}"
    state: present

- name: check if iso nfs share exists
  stat:
    path: /nfs/fs01/iso
  register: isoshare

- name: confirmation of directory
  debug:
    msg: "ISO share exists"
  when: isoshare.stat.isdir is defined

- name: create nfs share mount directory
  file:
    path: /nfs/fs01/iso
    state: directory
    mode: '0755'
    group: root
    owner: root
  when: isoshare.stat.isdir is not defined

- name: mount iso nfs share
  mount:
    fstype: nfs
    opts: defaults
    dump: '0'
    passno: '0'
    state: mounted
    src: fs01:/srv/iso
    path: /nfs/fs01/iso
  when: isoshare.stat.isdir is not defined

- name: configure /etc/dnsmasq.conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'

- name: configure /etc/default/dnsmasq
  lineinfile:
    path: /etc/default/dnsmasq
    line: "DNSMASQ_EXCEPT=lo"
    create: yes

- name: create pxelinux.cfg directory
  file:
    path: /var/lib/tftpboot/pxelinux.cfg/
    state: directory
    mode: '0755'
    group: root
    owner: root

- name: Create a symbolic link
  file:
    src: /nfs/fs01/iso
    dest: /var/lib/tftpboot/data
    owner: root
    group: root
    state: link

- name: configure pxe boot menu
  template:
    src: default.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/default

- name: copy syslinux template files to pxelinux.cfg directory
  copy:
    remote_src: yes
    src: "{{ item }}"
    dest: /var/lib/tftpboot
    force: no
  with_items:
      - /usr/share/syslinux/pxelinux.0
      - /usr/share/syslinux/menu.c32
      - /usr/share/syslinux/memdisk
      - /usr/share/syslinux/mboot.c32
      - /usr/share/syslinux/chain.c32
      - /usr/share/syslinux/vesamenu.c32

- name: link files to /var/lib/tftpboot/
  file:
    src: /usr/lib/syslinux/modules/bios/ldlinux.c32
    dest: /var/lib/tftpboot/ldlinux.c32
    owner: root
    group: root
    state: link

- name: copy pxe config for apache
  template:
    src: pxeboot.cfg.j2
    dest: /etc/httpd/conf.d/pxeboot.cfg

- name: allow apache to modify files
  sefcontext:
    target: '/var/lib/tftpboot/data(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: apply new SELinux file contexts
  command: restorecon -irv /var/lib/tftpboot/data
  notify:
  - restart dnsmasq
  - restart apache

- name: start tftp service
  service:
    name: tftp
    state: started