---
- name: install required packages
  yum:
    name: "{{ pxe_pkgs }}"
    state: present

- name: check if iso nfs share exists
  stat:
    path: /nfs/fs01/iso
  register: isoshare
  debug:
    msg: "ISO share exists"
  when: p.stat.isdir is defined

- name: create nfs share mount directory
  file:
    path: /nfs/fs01/iso
    state: directory
    mode: '0755'
    group: root
    owner: root
  when: isoshare.stat.isdir is not defined

- name: mount iso nfs share
  mount:
    fstype: nfs
    opts: defaults
    dump: '0'
    passno: '0'
    state: mounted
    src: fs01:/srv/iso
    path: /nfs/fs01/iso
  when: isoshare.stat.isdir is not defined

- name: configure /etc/dnsmasq.conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dsnmasq.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: create pxelinux.cfg directory
  file:
    path: /var/lib/tftpboot/pxelinux.cfg/
    state: directory
    mode: '0755'
    group: root
    owner: root

- name: create tftpboot data directory
  file:
    path: /var/lib/tftpboot/data
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create a symbolic link
  file:
    src: /nfs/fs01/iso
    dest: /var/lib/tftpboot/data
    owner: root
    group: root
    state: link

- name: configure pxe boot menu
  template:
    src: default.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/default

- name: copy syslinux template files to pxelinux.cfg directory
  copy:
    src: "{{ tftpboot_files }}"
    dest: "/var/lib/tftpboot"
    force: no

- name: copy pxe config for apache
  template:
    src: pxeboot.cfg.j2
    dest: /etc/httpd/conf.d/pxeboot.cfg

- name: allow apache to modify files
  sefcontext:
    target: '/var/lib/tftpboot/data(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: apply new SELinux file contexts
  command: restorecon -irv /var/lib/tftpboot/data
  notify:
  - restart dnsmasq
  - restart apache