---
- name: update all el packages and enable epel
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: update all debian packages
  apt:
    name: '*'
    state: latest
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: install and enable epel repo
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  
- name: install common el packages
  yum:
    name: "{{ common_pkgs }}"
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install common debian packages
  apt:
    name: "{{ common_pkgs }}"
    state: latest
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: mount nfs shares
  mount:
    fstype: nfs
    opts: defaults
    dump: '0'
    passno: '0'
    state: mounted
    src: fs01:/srv/shared
    path: /nfs/fs01/shared

- name: get AD packages for el
  become: true
  yum:
    name: "{{ ad_pkgs }}"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  notify:
    - restart realmd

- name: install AD debian packages
  apt:
    name: "{{ ad_pkgs }}"
    state: latest
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install pexpect using pip
  pip:
    name: pexpect

- name: check domain join status
  command: /bin/bash -c "/usr/sbin/realm list"
  register: realm_status

- name: join system to AD
  expect:
    command: /bin/bash -c "/usr/sbin/realm join --user={{ ad_join_account }}@{{ domain_name }} --computer-ou=OU=Domain\ Computers,DC={{ domain_caps }},DC={{ domain_suffix_caps }} {{ domain_name }}"
    responses:
      Password for *: "{{ bind_password }}"
  when: realm_status.stdout == ""

- name: Check if machine is bound
  shell: /bin/bash -c "realm list | grep sssd"
  register: realmd_bound
  changed_when: false
  ignore_errors: true

- name: Add default_domain_suffix to sssd.conf
  lineinfile: 
    dest: /etc/sssd/sssd.conf
    line: 'default_domain_suffix = {{ domain_name }}'
    insertafter: '^\[sssd\]'
  notify:
     - restart sssd
     - restart realmd
  when: realmd_bound|failed

- name: allow admin ad group logon privileges
  command: /bin/bash -c "/usr/sbin/realm permit -g {{ ad_admin_group }}@{{ domain_name }}"

- name: add admin ad group to sudoers
  lineinfile:
    dest: /etc/sudoers
    insertafter: '^%wheel'
    line: '%{{ ad_admin_group }}@{{ domain_name }}        ALL=(ALL)       ALL'