---
- name: update all el packages and enable epel
  yum:
    name: '*'
    state: latest
    enablerepo: "epel"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: update all debian packages
  apt:
    name: '*'
    state: latest
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  
- name: install common el packages
  yum:
    name: "{{ common_pkgs }}"
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install common debian packages
  apt:
    name: "{{ common_pkgs }}"
    state: latest
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: join to active directory
  become: true
  yum:
    name: "{{ ad_pkgs }}"
    state: present
  notify:
    - restart realmd

- name: join system to AD and add the computer object in the Linux OU
  command: /bin/bash -c "/usr/sbin/realm join --user={{ ad_join_account }}@{{ domain_name }} --password={{ ad_join_pass }} --computer-ou=OU=Domain\ Computers,DC={{ domain_caps }},DC={{ domain_suffix_caps }} {{ domain_name }}"

- name: Add default_domain_suffix to sssd.conf
  lineinfile: 
    dest: /etc/sssd/sssd.conf
    line: 'default_domain_suffix = {{ domain_name }}'
    insertafter: '^\[sssd\]'
  notify:
     - restart sssd
  when: realmd_bound|failed

- name: allow admin ad group logon privileges
  command: /bin/bash -c "/usr/sbin/realm permit -g {{ ad_admin_group }}@{{ domain_name }}"

- name: add admin ad group to sudoers
  lineinfile:
    dest: /etc/sudoers
    insertafter: '^%wheel'
    line: '%{{ ad_admin_group }}@{{ domain_name }}        ALL=(ALL)       ALL'