---
- name: run tasks for el-based hosts
  include_tasks:
    file: el.yml
  when: os_name == 'CentOS' or os_name == 'RedHat'

- name: run tasks for debian-based hosts
  include_tasks:
    file: deb.yml
  when: os_name == 'Ubuntu' or os_name == 'Debian'

- name: mount nfs shares
  mount:
    fstype: nfs
    opts: defaults
    dump: '0'
    passno: '0'
    state: mounted
    src: fs01:/srv/shared
    path: /nfs/fs01/shared

- name: join active directory
  include_tasks:
    file: join_ad.yml
  when: inventory_hostname != "FS01.VOID.LAB"

- name: set up krb5
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    backup: yes

- name: set up sssd
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    backup: yes

- name: restart sssd
  systemd:
    name: sssd
    state: restarted