---
- name: run tasks for el-based hosts
  include_tasks:
    file: el.yml
  when: ansible_os_family == 'RedHat'

- name: run tasks for debian-based hosts
  include_tasks:
    file: deb.yml
  when: ansible_os_family == 'Debian'

- name: mount nfs shares
  mount:
    fstype: nfs
    opts: defaults
    dump: '0'
    passno: '0'
    state: mounted
    src: fs01:/srv/shared
    path: /nfs/fs01/shared
  when: inventory_hostname != "FS01.VOID.LAB"

- name: join active directory
  include_tasks:
    file: join_ad.yml
  when: inventory_hostname != "FS01.VOID.LAB"

#- name: generate motd
