---
- name: add role from awx template
  hosts: "{{ awx_addrole_hosts }}"
  tasks:
    - name: iterate through supplied roles
      include_role:
        name: "{{ awx_template_roles }}"
      become: yes
      loop:
        - "{{ awx_addrole_roles }}"
      loop_control:
        loop_var: awx_template_roles