---
- name: create new vm
  hosts: localhost
  roles:
    - vmware-deploy

- name: install common-nix role if linux vm
  hosts: "{{ machine_ip }}"
  roles:
    - role: common-nix
      become: yes
      when: ansible_os_family != "Windows"

- name: apply additional roles if specified
  hosts: "{{ machine_ip }}"
  roles:
    - role: "{{ additional_roles }}"
      become: yes
      when: addtl_roles_selected == "yes"