---
common_pkgs:
  - wget
  - curl
  - screenfetch
  - vim-tiny
  - htop

ad_pkgs:
  - realmd
  - sssd
  - oddjob 
  - oddjob-mkhomedir 
  - adcli
  - samba-common
  - samba-common-tools 
  - krb5-workstation 
  - authselect-compat