---
- name: Check libuv zip exists
  stat:
    path: /opt/emulators/disks/dps8/libuv-1.x.zip
  register: libuv_result

- name: fetch libuv for dps8
  get_url:
    url: https://github.com/libuv/libuv/archive/v1.x.zip
    dest: /opt/emulators/dps8/
  when: not libuv_result.stat.exists
  register: libuv_download

- name: unzip libuv
  unarchive:
    src: /opt/emulators/dps8/libuv-1.x.zip
    dest: /opt/emulators/dps8/
    remote_src: yes
  when: libuv_download.changed

- name: run autogen script for libuv
  command: /bin/sh -C '/opt/emulators/dps8/libuv-1.x/autogen.sh'
  args:
    creates: /opt/emulators/dps8/libuv-1.x/Makefile.in

- name: configure libuv for compiling
  command: /bin/sh -C '/opt/emulators/dps8/libuv-1.x/./configure'
  args:
    creates: /opt/emulators/dps8/libuv-1.x/Makefile

- name: make libuv
  make:
    chdir: /opt/emulators/dps8/libuv-1.x
  register: libuv_make

- name: make install libuv
  make:
    chdir: /opt/emulators/dps8/libuv-1.x
    target: install
  when: libuv_make.changed == true

- name: create src directory
  file:
    path: /opt/emulators/dps8/git
    state: directory

- name: clone dps8 source
  git:
    repo: https://gitlab.com/dps8m/dps8m.git
    dest: /opt/emulators/dps8/git
    version: "R2.0"

- name: build dps8 from source
  make:
    chdir: /opt/emulators/dps8/git
  register: dps8_build

- name: link lubuv.so.1 to /lib64
  file:
    src: /usr/local/lib/libuv.so.1.0.0
    dest: /lib64/libuv.so.1
    owner: root
    group: root
    state: link

- name: link dps8 binary to /usr/local/bin
  file:
    src: /opt/emulators/dps8/git/src/dps8/dps8
    dest: /usr/local/bin/dps8
    owner: root
    group: root
    state: link

- name: Check Multics disk zip exists
  stat:
    path: /opt/emulators/disks/simh/QuickStart_MR12.6f.zip
  register: multics_result

- name: fetch Multics disk
  get_url:
    url: https://s3.amazonaws.com/eswenson-multics/public/releases/MR12.6f/QuickStart_MR12.6f.zip
    dest: /opt/emulators/simh
  when: not multics_result.stat.exists
  register: multics_download

- name: unzip Multics disk
  unarchive:
    src: /opt/emulators/simh/QuickStart_MR12.6f.zip
    dest: /opt/emulators/disks/dps8/
    remote_src: yes
  when: multics_download.changed