- name: get prerequisite packages
  yum:
    name: "{{ retroemu_pkgs }}"
    enablerepo: PowerTools
    state: present

- name: make directory for emulators
  file:
    path: "/opt/emulators/{{ item }}"
    state: directory
  with_items:
    - dps8
    - simh
    - qemu

- name: create disks directory
  file:
    path: "/opt/emulators/disks/{{ item }}"
    state: directory
  with_items:
    - dps8
    - simh
    - qemu

- name: mount iso share
  mount:
    fstype: nfs
    opts: defaults
    dump: '0'
    passno: '0'
    state: mounted
    src: fs01:/srv/iso
    path: /nfs/fs01/iso

- name: install dps8
  include_tasks:
    file: dps8.yml

- name: install simh & compile pdp11
  include_tasks:
    file: simh.yml

- name: configure qemu and Mac OS 9.2
  include_tasks:
    file: qemu.yml

- name: open firewall ports
  firewalld:
    port: "{{ retroemu_ports }}"
    permanent: yes
    state: enabled

- name: open firewall for telnet
  firewalld:
    service: telnet
    permanent: yes
    state: enabled

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
