- name: get prerequisite packages
  yum:
    name: "{{ retroemu_pkgs }}"
    enablerepo: PowerTools
    state: present

- name: make directory for emulators
  file:
    path: "/opt/emulators/{{ retroemu_dirs }}"
    state: directory

- name: install dps8
  include_tasks:
    file: dps8.yml

- name: install simh & compile pdp11
  include_tasks:
    file: simh.yml

- name: configure qemu and Mac OS 9.2
  include_tasks:
    file: qemu.yml

- name: open firewall ports
  firewalld:
    port: "{{ retroemu_ports }}"
    permanent: yes
    state: enabled

- name: open firewall for telnet
  firewalld:
    service: telnet
    permanent: yes
    state: enabled

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
