---

- name: get newer qemu source
  git:
    repo: git://git.qemu-project.org/qemu.git
    dest: /opt/emulators/qemu/

- name: create build directory
  file:
    path: /opt/emulators/qemu/build
    state: directory

- name: configure qemu for compiling
  command: /bin/sh -C './configure'
  chdir: /opt/emulators/qemu/

- name: build qemu
  make:
    chdir: /opt/emulators/qemu/
    
## Needs completed