---
- name: check for qemu source files before proceeding
  find:
    paths: /opt/emulators/qemu
    patterns: "*.*"
  register: qemu_files

- name: get qemu source
  git:
    repo: git://git.qemu-project.org/qemu.git
    dest: /opt/emulators/qemu/
  when: qemu_files.matched == 0

- name: configure qemu for compiling
  shell: "{{ item }}"
  args:
    chdir: /opt/emulators/qemu/
    creates: "/usr/bin/qemu-img"
  with_items:
    - ./configure
    - make

- name: Allow external viewing of VNC
  replace:
    path: /etc/libvirt/qemu.conf
    regexp: '^#(.*vnc_listen.*)'
    replace: 'vnc_listen = "0.0.0.0"'
  
- name: copy mac os 9 iso
  copy:
    src: /nfs/fs01/iso/MacOS9/{{ macos9_iso }}
    dest: /opt/emulators/disks/qemu/{{ macos9_iso }}
    remote_src: yes

- name: create mac os 9 hd img
  shell: qemu-img create -f qcow2 {{ macos9_hd_img }} {{ macos9_hd_size }}
  args:
    chdir: /opt/emulators/disks/qemu
    creates: /opt/emulators/disks/qemu/{{macos9_hd_img}}

- name: copy os 9 install script
  template:
    src: macos9-install.sh.j2
    dest: /opt/emulators/qemu/macos9-install.sh
    mode: '0755'

- name: copy os 9 boot script
  template:
    src: macos9-boot.sh.j2
    dest: /opt/emulators/qemu/macos9-boot.sh
    mode: '0755'

- name: link install script to /usr/local/bin
  file:
    src: /opt/emulators/qemu/macos9-install.sh
    dest: /usr/local/bin/macos9-install
    state: link

- name: link boot script to /usr/local/bin
  file:
    src: /opt/emulators/qemu/macos9-boot.sh
    dest: /usr/local/bin/macos9-boot
    state: link

- name: restart libvirtd
  systemd:
    service: libvirtd
    state: restarted
