---
- name: set up new vm
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "/{{ vmware_datacenter}}/vm"
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ new_vm_name }}"
    state: present
    guest_id: centos64Guest
    # This is hostname of particular ESXi server on which user wants VM to be deployed
    esxi_hostname: "{{ esxi_hostname }}"
    disk:
    - size_gb: 20
      type: thin
      datastore: "{{ esxi_datastore }}"
    hardware:
      memory_mb: "{{ vm memory_mb }}"
      num_cpus: "{{ vm_num_cpus }}"
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
  delegate_to: localhost
  register: deploy_vm

- name: change vm boot boot order
  vmware_guest_boot_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ new_vm_name }}"
    boot_order:
      - ethernet
      - cdrom
      - disk
      - floppy
  notify:
    - power on vm