---
- name: set up new vm
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "/{{ vmware_datacenter}}/vm"
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ new_vm_name }}"
    state: present
    guest_id: centos64Guest
    esxi_hostname: "{{ esxi_hostname }}"
    disk:
    - size_gb: 20
      type: thin
      datastore: "{{ esxi_datastore }}"
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ vm_num_cpus }}"
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
  delegate_to: localhost
  register: deploy_vm

- name: change vm boot order for pxe
  vmware_guest_boot_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ new_vm_name }}"
    boot_order:
      - ethernet
      - cdrom
      - disk
      - floppy

- name: Gather some info from a guest using the vSphere API output schema
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ new_vm_name }}"
    schema: "vsphere"
    properties: ["config.hardware.device[-1].macAddress"]
  delegate_to: localhost
  register: new_vm_facts

- name: create pxe config file for the vm
  include_role:
    name: create-vm-pxecfg

- name: power on vm
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ new_vm_name }}"
    state: poweredon

- name: change vm boot order back for post-install
  vmware_guest_boot_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ new_vm_name }}"
    boot_order:
      - disk
      - cdrom
      - ethernet
      - floppy

- name: wait for installation to finish
  wait_for_connection:
    timeout: 600
  delegate_to: "{{ machine_ip }}"
  