---
- name: set up new vm
  vmware_guest:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    folder: "/{{ vmware_datacenter}}/vm"
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ new_vm_name }}"
    state: present
    guest_id: centos64Guest
    esxi_hostname: "{{ esxi_hostname }}"
    disk:
    - size_gb: 20
      type: thin
      datastore: "{{ esxi_datastore }}"
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ vm_num_cpus }}"
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
  delegate_to: localhost
  register: deploy_vm

- name: change vm boot order for pxe
  vmware_guest_boot_manager:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    name: "{{ new_vm_name }}"
    boot_order:
      - ethernet
      - cdrom
      - disk
      - floppy

- name: get network adapter settings of virtual machine
  vmware_guest_network:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    datacenter: "{{ vmware_datacenter }}"
    validate_certs: no
    name: "{{ new_vm_name }}"
    gather_network_info: true
  delegate_to: localhost
  register: new_vm_facts

- name: create pxe config file for the vm
  include_role:
    name: create-vm-pxecfg

- name: power on vm
  vmware_guest:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    name: "{{ new_vm_name }}"
    state: poweredon

- name: change vm boot order back for post-install
  vmware_guest_boot_manager:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    name: "{{ new_vm_name }}"
    boot_order:
      - disk
      - cdrom
      - ethernet
      - floppy

- name: add new vm to inventory
  add_host:
    hostname: "{{ machine_ip }}"

- name: wait for installation to finish
  wait_for_connection:
    #delay: 300
    timeout: 600
  delegate_to: "{{ machine_ip }}"

- name: create dns record
  win_dns_record:
    name: "{{ machine_hostname }}"
    type: "A"
    value: "{{ machine_ip }}"
    zone: "{{ site_domain_name }}"
  delegate_to: VDC01.VOID.LAB

- name: create ptr record
  win_dns_record:
    name: "{{ machine_ip }}"
    type: "PTR"
    value: "{{ machine_hostname }}"
    zone: "2.0.10.in-addr.arpa"
  delegate_to: VDC01.VOID.LAB

- name: gather facts of new vm
  setup:
  delegate_to: "{{ machine_ip }}"

- name: set up krb5
  become: yes
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    backup: yes
  delegate_to: "{{ machine_ip }}"

- name: restart sssd
  become: yes
  systemd:
    name: sssd
    state: restarted
  delegate_to: "{{ machine_ip }}"
  when: os_name != "Windows" or os_name != "FreeBSD"