---
- name: install pkgs
  yum:
    name: "{{ nixctl_pkgs }}"
    state: present

- name: enable repos
  yum:
    enablerepo: "{{ item }}"
  with_items:
    - "PowerTools"
    - "epel"

- name: install x11
  yum:
    name: "@base-x"
    state: present

- name: install kde plasma
  yum:
    name: "@kde-desktop-environment"
    state: present
    skip_broken: yes
    enablerepo: "{{ item }}"
  with_items:
    - "epel"
    - "PowerTools"

- name: create vnc service
  template:
    src: vncserver.j2
    dest: /etc/systemd/system/vncserver@.service

- name: link vnc service
  file:
    src: /etc/systemd/system/vncserver.service
    dest: "/etc/systemd/system/multi-user.target.wants/vncserver@:1.service"
    state: link

- name: create home dir and vnc directory
  file:
    path: /home/{{ lookup('env', 'AD_USERNAME').split("@")[0] }}/.vnc
    state: directory
    owner: ccasares
    group: "domain admins"
    

- name: create xstartup
  template:
    src: xstartup.j2
    dest: /home/{{ lookup('env', 'AD_USERNAME').split("@")[0] }}/.vnc/xstartup

- name: start vnc service
  systemd:
    service: vncserver@:1
    state: started
    enabled: yes