---
- name: create local share admins group
  group:
    name: fsadmins
    state: present

- name: create fs directories
  block:
    - name: checking fs folder structure
      stat:
       path: "{{ item }}"
      register: folder_stats
      with_items:
      - ["/srv/shared","/srv/iso","/srv/chad"]
    - name:
      file:
       path: "{{ item.item }}"
       state: directory
       mode: 0755
       group: root
       owner: fsadmins
      when: item.stat.exists == false
      with_items:
      - "{{folder_stats.results}}"