---

#- name: create fs directories
#  block:
#    - name: checking fs folder structure
#      stat:
#        path: "{{ fs_root_path}}/{{ item }}"
#      with_items: "{{ fs_paths }}"
#      register: folder_stats
#    - name: creating directories
#      file:
#        path: "{{ fs_root_path }}/{{ item }}"
#        state: directory
#        mode: 0775
#        group: root
#        owner: fsadmins
#      with_items: "{{ fs_paths }}"
#      when: fs_paths.stat.exists == false#

- name: install nfs-server
  yum:
    name: nfs-utils
    state: present

- name: configure nfs nfs-server
  template:
    src: exports.j2
    dest: /etc/exports
    mode: '0644'
    owner: root
    group: root
    backup: yes

- name: start nfs-server
  systemd:
    service: nfs-server
    state: started
    enabled: yes

- name: install samba packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ smb_pkgs }}"

- name: configure samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: '0644'
    owner: root
    group: root
    backup: yes

- name: update nsswitch.conf
  lineinfile:
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line }}"
    dest: "/etc/nsswitch.conf"
  with_items:
    - { regexp: '^passwd:', line: 'passwd:		sss winbind files' }
    - { regexp: '^group:' , line: 'group:		  sss winbind files' }

- name: check domain join status
  command: /bin/sh -c "/usr/sbin/realm list"
  register: realm_winbind_status

- name: join to ad with winbind
  include_tasks: join_ad_winbind.yml
  when: realm_winbind_status.stdout == ""

- name: start samba
  systemd:
    service: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - smb
    - nmb

#- name: populate iso share with current isos
#  block:
#    - name: checking iso folder structure
#      stat:
#       path: "{{ iso_root_path}}/{{ iso_paths }}"
#      register: iso_folder_stats
#    - name: creating directories
#      file:
#       path: "{{ iso_folder_stats.results }}"
#       state: directory
#       mode: '0755'
#       group: root
#       owner: fsadmins
#      when: iso_paths.stat.exists == false
#    - name: download centos-current
#    - name: download redhat-curent
#    - name: download freebsd-current
#    - name: download alpine-current
#    - name: download debian-current
#    - name: download ubuntu-current
#    - name: download openbsd-current
#    - name: download kali-current
#    - name: download windows-current
#    - name: download vmware-current