---
# get packages
# copy files ( set up github backup? )
# set permissions
# install php extensions
# enable mcrypt php extension -- pecl install mcrypt-1.0.3 -- add extension=mcrypt.so after ;extension=mbstring in /etc/php/7.3/apache2/php.ini
# enable services
# set up certbot
# set up auto-renew for certbot in cron

- name: get packages

- name: place website files
  file:
    src: websitefiles.zip
    dest: /tmp/websitefiles.zip

- name: unzip website files
  unzip:
    src: /tmp/websitefiles.zip
    dest: "{{ apache_document root}}"

# The following lines depend whether or not I move over to wikimedia or another wiki service
#- name: install php extensions

#- name: insall mcrypt

#- name: add mcrypt extension to php conf

# Need to figure out how to do this
#- name: run certbot
#  acme_certificate:

- name: install crontab for cert renewal
  cron:
    hour: "0"
    minute: "0"
    day: "15"
    job: "certbot renew --apache --keep-until-expiring --quiet --agree-tos"

- name: enable and start apache
  systemd:
    service: apache2
    state: started
    enabled: yes