---
- name: power on vm
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ new_vm_name }}"
    state: poweredon

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: restart apache
  systemd:
    name: httpd
    state: restarted