---
- name: set lowercase mac address
  set_fact: new_vm_pxe_mac="{{ new_vm_facts[new_vm_name].mac_address | regex_replace(':', '-') | lower }}"

- name: create mac file
  hosts: PXE01
  template:
    src: pxecfg.j2
    dest: "/var/lib/tftpboot/pxeboot.cfg/01-{{ new_vm_pxe_mac }}"
  notify:
    - power on vm