---
- name: include PXE01 vars
  include_vars:
    file: roles/pxeboot/vars/main.yml

- name: show virtual machine parameters
  debug:
    msg: "{{ new_vm_facts.virtual_machines }}"

- name: set lowercase mac address
  set_fact: new_vm_pxe_mac="{{ new_vm_facts.virtual_machines[0].mac_address[0] | regex_replace(':', '-') | lower }}"

- name: set hostname
  set_fact: machine_hostname="{{ new_vm_facts.virtual_machines[0].guest_name | lower }}.{{ site_domain_name }}"

- name: create custom kickstart file
  become: yes
  template:
      src: kickstart.conf.j2
      dest: "/var/www/html/ks/{{ new_vm_name | lower }}.conf"
      backup: yes
  delegate_to: PXE01

- name: allow apache to modify files
  become: yes
  sefcontext:
    target: '/var/www/html(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  delegate_to: PXE01

- name: apply new SELinux file contexts
  become: yes
  command: restorecon -irv /var/www/html
  delegate_to: PXE01

- name: create mac file
  become: yes
  template:
    src: pxecfg.j2
    dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ new_vm_pxe_mac }}"
  delegate_to: PXE01

- name: restart services
  become: yes
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - dnsmasq
    - tftp
    - httpd
  delegate_to: PXE01

- name: finish up
  debug:
    msg: "Configuration on PXE01 complete"