---

- name: include PXE01 vars
  include_vars:
    file: roles/pxeboot/vars/main.yml

- name: print vm facts
  debug:
    var: new_vm_facts.virtual_machines

- name: set lowercase mac address
  set_fact: new_vm_pxe_mac="{{ new_vm_facts.virtual_machines[0].mac_address[0] | regex_replace(':', '-') | lower }}"

- name: create custom kickstart file
  become: yes
  template:
      src: kickstart.ks.j2
      dest: "/var/www/html/ks/{{ new_vm_name }}.ks"

- name: create mac file
  become: yes
  template:
    src: pxecfg.j2
    dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ new_vm_pxe_mac }}"
  delegate_to: PXE01
  notify:
    - power on vm