---
- name: include PXE01 vars
  include_vars:
    file: roles/pxeboot/vars/main.yml

#- name: set lowercase mac address
# set_fact: new_vm_pxe_mac="{{ new_vm_facts.virtual_machines[0].mac_address[0] | regex_replace(':', '-') | lower }}"

- name: Get UUID from given VM Name
  debug:
    msg: "{{ item.uuid }}"
  with_items:
    - "{{ deploy_vm.virtual_machines | json_query(query) }}"
  vars:
    query: "[?guest_name=='PXE01']"

- name: get mac address
  set_fact: new_vm_pxe_mac_pre="{{ item.mac_address[0] }}"
  with_items:
    - "{{ new_vm_facts.virtual_machines | json_query(query) }}"
  vars:
    query: "[?guest_name==[new_vm_name]]"

- name: reformat mac address
  set_fact: new_vm_pxe_mac="{{ new_vm_pxe_mac_pre | regex_replace(':', '-') | lower }}"

- name: can you fucking print it please?
  debug:
    msg: "{{ new_vm_facts.virtual_machines }}"

- name: set hostname
  set_fact: machine_hostname="{{ new_vm_name | lower }}.{{ site_domain_name }}"

- name: create custom pxelinux-cfg file
  become: yes
  template:
    src: pxecfg.j2
    dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ new_vm_pxe_mac }}"
    backup: yes
  delegate_to: PXE01

- name: create custom kickstart file
  become: yes
  template:
      src: kickstart.conf.j2
      dest: "/var/www/html/ks/{{ new_vm_name }}.conf"
      backup: yes
  delegate_to: PXE01

- name: allow apache to modify files
  become: yes
  sefcontext:
    target: '/var/www/html(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  delegate_to: PXE01

- name: apply new SELinux file contexts
  become: yes
  command: restorecon -irv /var/www/html
  delegate_to: PXE01

- name: create mac file
  become: yes
  template:
    src: pxecfg.j2
    dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ new_vm_pxe_mac }}"
  delegate_to: PXE01

- name: restart services
  become: yes
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - dnsmasq
    - tftp
    - httpd
  delegate_to: PXE01

- name: finish up
  debug:
    msg: "Configuration on PXE01 complete"