---
- handlers:
  include: roles/vmware-deploy/handlers/main.yml

- name: set lowercase mac address
  set_fact: new_vm_pxe_mac="{{ new_vm_facts.virtual_machines[new_vm_name].mac_address | regex_replace(':', '-') | lower }}"

- name: create mac file
  template:
    src: pxecfg.j2
    dest: "/var/lib/tftpboot/pxeboot.cfg/01-{{ new_vm_pxe_mac }}"
  delegate_to: PXE01
  notify:
    - power on vm