---
- name: include PXE01 vars
  include_vars:
    file: roles/pxeboot/vars/main.yml

#- name: set lowercase mac address
# set_fact: new_vm_pxe_mac="{{ new_vm_facts.virtual_machines[0].mac_address[0] | regex_replace(':', '-') | lower }}"

- name: get mac address
  set_fact: new_vm_pxe_mac_pre="{{ new_vm_facts }}"

- name: print vm with_items
  debug:
    msg: "{{ new_vm_pxe_mac_pre['network_data']['0']['mac_addr'] }}"

- name: reformat mac address
  set_fact: new_vm_pxe_mac="{{ new_vm_pxe_mac_pre['network_data']['0']['mac_addr'] | regex_replace(':', '-') | lower }}"

- name: set hostname
  set_fact: machine_hostname="{{ new_vm_name | lower }}.{{ site_domain_name }}"

- name: create custom pxelinux-cfg file for el linux
  become: yes
  template:
    src: el-pxecfg.j2
    dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ new_vm_pxe_mac }}"
    backup: yes
  delegate_to: PXE01
  when: os_name == 'CentOS' or os_name == 'RedHat'

- name: create custom pxelinux-cfg file for debian-based distros
  become: yes
  template:
    src: deb-pxecfg.j2
    dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ new_vm_pxe_mac }}"
    backup: yes
  delegate_to: PXE01
  when: os_name == 'Debian' or os_name == "Ubuntu"

- name: create custom pxelinux-cfg file for freebsd
  become: yes
  template:
    src: bsd-pxecfg.j2
    dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ new_vm_pxe_mac }}"
    backup: yes
  delegate_to: PXE01
  when: os_name == 'FreeBSD' or os_name == 'OpenBSD'

- name: create custom kickstart file
  become: yes
  template:
    src: kickstart.conf.j2
    dest: "/var/www/html/ks/{{ new_vm_name }}.conf"
    backup: yes
  delegate_to: PXE01
  when: os_name == 'CentOS' or os_name == 'RedHat'

- name: create custom preseed file
  become: yes
  template:
    src: preseed.cfg.j2
    dest: "/var/www/html/preseed/{{ new_vm_name }}.cfg"
    backup: yes
  delegate_to: PXE01
  when: os_name == 'Debian' or os_name == 'Ubuntu'

- name: create custom installerconfig file for bsd-pxecfg.j2
  become: yes
  template:
    src: installerconfig.j2
    dest: "/var/www/html/bsd/installerconfig"
    backup: yes
  delegate_to: PXE01
  when: os_name == 'FreeBSD' or os_name == 'OpenBSD'

- name: force httpd_use_nfs bool
  seboolean:
    name: httpd_use_nfs
    state: yes
    persistent: yes

- name: allow apache to modify files
  become: yes
  sefcontext:
    target: '/var/www/html(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  delegate_to: PXE01

- name: apply new SELinux file contexts
  become: yes
  command: restorecon -irv /var/www/html
  delegate_to: PXE01

#- name: restart services
#  become: yes
#  systemd:
#    name: "{{ item }}"
#    state: restarted
#    enabled: yes
#  with_items:
#    - dnsmasq
#    - tftp
#    - httpd
#  delegate_to: PXE01

- name: finish up
  debug:
    msg: "Configuration on PXE01 complete"