---
- name: start nfs-server
  systemd:
    service: nfs-server
    state: started

- name: start samba
  systemd:
    service: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - smb
    - nmb

- name: start winbind
  systemd:
    service: winbind
    state: started
    enabled: yes