---
- name: install required packages
  yum:
    name: "{{ pxe_pkgs }}"
    state: present

- name: configure /etc/dnsmasq.conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dsnmasq.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - restart dnsmasq
